declare module '*.module.css'
declare module '*.module.scss'
declare module '*.module.sass'

declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.svg'
declare module '*.gif'
declare module '*.webp'
